version: '3'
services:
  zigbee2mqtt:
      image: koenkk/zigbee2mqtt:latest-dev
      volumes:
        - ./zigbee2mqtt/data:/app/data
      devices:
        - /dev/ttyUSB0:/dev/ttyUSB0
      restart: always
      network_mode: host
  knsmart-server:
    build: ./server
    restart: always
    network_mode: host
  knsmart-client:
    build: ./client
    restart: always
    network_mode: host
