  version: '3'
  services:
    zigbee2mqtt:
      container_name: zigbee2mqtt
      image: koenkk/zigbee2mqtt:latest-dev
      volumes:
        - ./data:/app/data
      devices:
        - /dev/ttyUSB0:/dev/ttyUSB0
      restart: always
      network_mode: host
